version: "3"
services:
  app:
    image: ghcr.io/thinc-org/sport-complex-booking-frontend:dev
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=shared"
      - "traefik.http.routers.frontend-staging.entrypoints=websecure"
      - "traefik.http.routers.frontend-staging.rule=Host(`staging.sc-prod.suphon.dev`)"
      - "traefik.http.routers.frontend-staging.tls=true"
      - "traefik.http.routers.frontend-staging.tls.certresolver=letsencrypt"
    networks:
      - shared
networks:
  shared:
    external:
      name: shared
